services:
  authservice:
    image: auth_service:latest
    build: .
    ports:
      - "8083:8080"
    depends_on:
      postgres_authservice:
        condition: service_healthy
    environment:
      DB_HOST: postgres_authservice
      DB_PORT: 5432
      DB_USER: rumronya
      DB_PASSWORD: password
      DB_NAME: auth

  postgres_authservice:
    image: postgres:15
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: rumronya
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pgdata_authservice:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rumronya -d auth"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata_authservice: