spring.application.name=authenticationservice
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db.changelog/db.changelog-master.xml

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/auth
spring.datasource.username=${DB_USER:rumronya}
spring.datasource.password=${DB_PASSWORD:password}

jwt.secret=w4I7q9nGxXcZKL1PyAeNZo5GF9Q1JxQ9FLtbL+XYFtg=